- LIB/nesdash.s
Fixes glitchy graphics in levels
> Fix off by one error in attribute loading

- SAUCE/famidash.h
- SAUCE/functions/sprite_loading.h
Blue pads speed should be a constant and not depend on the original Y speed
> Fix blue pads gravity

- LIB/nesdash.s
> Bugfix because i am a dumbass

- SAUCE/functions/collision.h
Snapping is not allowed and will be sanctioned with a 500$ bill.
> Re-fix snapping

- SAUCE/functions/collision.h
- SAUCE/functions/sprite_loading.h
- SAUCE/functions/x_movement.h
- SAUCE/gamemodes/gamemode_ball.h
- SAUCE/gamemodes/gamemode_cube.h
- SAUCE/gamemodes/gamemode_ship.h
- SAUCE/gamemodes/gamemode_spider.h
- SAUCE/gamemodes/gamemode_ufo.h
Should be more efficient and better to read.
> Rewrote the whole collision routine

- SAUCE/functions/collision.h
> Oops there was some zipping

- METATILES/metatiles.inc
- SAUCE/functions/collision.h
> Add col right - col left deaths

- SAUCE/functions/collision.h
I made half death coll better (no more jumping on it), used char temps as da optimizer suggested and optimized a lil bit coll_death.
> Collision tweaks

- SAUCE/functions/collision.h
- SAUCE/gamemodes/gamemode_ship.h
- SAUCE/gamemodes/gamemode_ufo.h
> Fix moar coll bugs

- SAUCE/gamemodes/gamemode_ball.h
> Fix ball inside spikes

- SAUCE/functions/collision.h
- SAUCE/gamemodes/gamemode_ball.h
> Tweaks to left and right death col hitbox

- SAUCE/gamemodes/gamemode_ball.h
> More ball tweaks

- SAUCE/functions/collision.h
- SAUCE/functions/x_movement.h
> Fix dry out even more

- SAUCE/functions/collision.h
- SAUCE/functions/x_movement.h
You know what? Lets make another coll routine just for the spike check
> Actually better fix for the ground spike issue

- LIB/nesdash.h
- LIB/nesdash.s
- LIB/neslib.s
- SAUCE/defines/menutext.h
- SAUCE/famidash.c
- SAUCE/famidash.h
- SAUCE/gamestates/state_menu.h
- Menus now have arrow routines not via giant af switch cases
- MUSIC PLAYS AUTOMATICALLY WHILE FADING IN/OUT, REDUCING PERCEIVED LAG
> Optimized menus

- LIB/nesdash.s
- cmpdbgfiles.py
> .proc'd some routines, table'd _movement

- CONFIG/mmc3.cfg
- LIB/nesdash.h
- LIB/nesdash.s
- LIB/neslib.s
- SAUCE/defines/sprites.h
- SAUCE/famidash.h
- SAUCE/functions/level_loading.h
- SAUCE/functions/reset_level.h
- SAUCE/gamestates/state_game.h
size increased by 132 bytes, BUT it's better now lmao
> Cube rotation, new flipping routine, collision buffers now in SRAM

- SAUCE/famidash.h
> tweak ufo jump

- SAUCE/functions/collision.h
> Fix small spike hitbox

- CONFIG/mmc3.cfg
- LIB/nesdash.h
- LIB/nesdash.s
- LIB/nesdoug.s
- LIB/neslib.h
- LIB/neslib.s
- METATILES/metatiles_macro.inc
- SAUCE/defines/menutext.h
- SAUCE/famidash.c
- SAUCE/functions/draw_sprites.h
- SAUCE/functions/level_loading.h
- SAUCE/gamestates/state_demo.h
- SAUCE/gamestates/state_game.h
- SAUCE/gamestates/state_lvldone.h
- SAUCE/gamestates/state_menu.h
- cmpdbgfiles.py
- makefile
Diff tool output:
`CODE:        7280 → 7210 - diff:  70`
`RODATA:      672  → 468  - diff:  204`
`CODE_2:      5962 → 4549 - diff:  1413`
`STARTUP:     1971 → 237  - diff:  1734`
`XCD_BANK_03: 7551 → 7457 - diff:  94`
`LVL_BANK_00: 2423 → 2445 - diff: -22`
`NESLIB:      0    → 1727 - diff: -1727`
`NESDOUG:     0    → 1489 - diff: -1489`
Total size reduction: 277 bytes
mostly done in the menu, but also some other places
> OPTIMIZATIONS MOTHERFU-

- SAUCE/gamemodes/gamemode_wave.h
- SAUCE/gamestates/state_game.h
> Fix wave vibration

- LIB/nesdash.s
> Fix wave x3 and x4

- SAUCE/functions/collision.h
- SAUCE/functions/x_movement.h
> Ultra fix platformer wall collision

- CONFIG/mmc3.cfg
> Fix compiling

- SAUCE/functions/collision.h
- SAUCE/gamestates/state_game.h
What happened is basically bro checked the spike at the left and said: thats enough im not checking the block at the other side. Then the next frame the cube is inside the block and the side collision said: holy shit im inside a block so bro died
> Fix cube dying to floor

- SAUCE/famidash.h
- SAUCE/functions/draw_sprites.h
- SAUCE/gamestates/state_game.h
> Better trail

- SAUCE/functions/draw_sprites.h
- SAUCE/functions/reset_level.h
this doesn't compile because of memory overflow, alex will optimize it
> Fix things

- SAUCE/functions/collision.h
- SAUCE/gamestates/state_game.h
> Fix cube dying at the start

- SAUCE/functions/collision.h
I sure do hope slopes didn't need it
> Oops removed something in accident

- SAUCE/functions/collision.h
> Fixed collision for the 81st time

- SAUCE/functions/collision.h
> Unfix ground spikes

- SAUCE/functions/collision.h
- SAUCE/gamestates/state_game.h
I keep reintroducing existential damage on accident
> Fix some issues

- SAUCE/functions/collision.h
- SAUCE/gamestates/state_game.h
Plus other stuff like the speed dependant slope launch (slopes are broken still) and of course a funny useless merge branch commit
> Fix Kando's funny mini blocks

- SAUCE/functions/collision.h
> Fix collision

- SAUCE/functions/collision.h
> I fogot to reset the y pos

- LIB/asm/nesdash.s
- LIB/headers/nesdash.h
- SAUCE/famidash.h
- SAUCE/functions/level_loading.h
- SAUCE/gamestates/state_lvldone.h
- SAUCE/gamestates/state_menu.h
this code request was coded 100% in a skirt
> printdecimal function

- LIB/asm/neslib.s
- SAUCE/gamestates/state_lvldone.h
colors when transitioning to the level end screen
> fix off by one preventing bg colors from updating and also turn off

- SAUCE/gamestates/state_menu.h
First pull request, the old transition code has been kind of bugging me, I'm not gonna lie.
I found that the screen doesn't change color when switching levels. I'll check now if I messed something up.
> Add smoother level select transition

- LEVELS/ADDING A NEW LEVEL.txt
Really needed thingy. Please add this to all branches
> Guide on how to add a level
